# set name of your service
name: ztrack
# default paramenters
env: {{ ENV }}
listen: "{{HOST|default('0.0.0.0')}}:{{PORT|default(8080)}}"
redis_dsn: "{{REDIS_DSN|default('redis://redis:6379')}}"
ch_dsn: "{{CHP_DSN|default('http://default:default@host:9090')}}"

rpc_params:
  listen_enrich: yes

props:
    key: key
    phone: data.called_did
    event: data.event
use_keys:
    - in.gen.ztrack.main
